### ISSUE TITLE
Wrong dates in remainder email

### ISSUE THREAD

**Issue by hunainaslam** [totara/facetoface-2.0#5]
If you have multiple sessions added and all sessions have any custom filed like location, the attendees do receive remainder emails but in the emails the custom fields have wrong data. For example if one users has signed up for Melbourne session and the other for Sydney location they might receive wrong locations.

**Comment by hunainaslam** [comment]
Here is the solution to the problem:
Look for this line in unction facetoface_email_substitutions(..)

$customdata = $DB->get_records('facetoface_session_data', array('sessionid' => $data->id), '', 'fieldid, data');

Replace it with the following line

$customdata = $DB->get_records('facetoface_session_data', array('sessionid' => $sessionid), '', 'fieldid, data');

This will resolve the issue.

**Comment by cirvine** [comment]
Hi,
This is an old version of Facetoface which is no longer actively maintained. The current maintained community version can be found here: https://moodle.org/plugins/view.php?plugin=mod_facetoface

**Comment by hunainaslam** [comment]
Hi 

This version also has the same problem. I have tested it and it causes the same problem

**Comment by cirvine** [comment]
Yes but this version is not actively maintained - there have been no commits to this repository since January 2013. It is old, essentially obsolete code and there are no plans to change that situation. The primary purpose of this particular repository was to provide an upgrade from the old Moodle 1.9 plugin to the 2.2 series, at the time Totara was porting all our code to 2.2. The current real, actively maintained, community version is the one in the link I provided above.
